[mysqld]

# Light optimizations for local development
skip-external-locking
key_buffer_size=16M
max_allowed_packet=16M
table_open_cache=128
sort_buffer_size=512K
net_buffer_length=8K
read_buffer_size=256K
read_rnd_buffer_size=512K

# InnoDB
innodb_buffer_pool_size=128M
innodb_log_file_size=48M
innodb_file_per_table=1
innodb_undo_tablespaces=1
innodb_undo_log_truncate=1
aria_log_file_size=32M
aria_log_purge_type=immediate

# Other parameters like datadir, plugin-dir, port, etc. are passed directly to the server by GumPress
