version = 1

[*]
flash-attn = on
no-mmap = false
threads = 4
log-disable = on
models-max = 2

# Embeddings Model
[emb-model]
model = all-minilm-l6-v2-q4_k_m.gguf
embeddings = on
n-gpu-layers = 999

# Completion Model (default-model = true coming soon)
[com-model]
model = smollm2-135m-instruct-q4_k_m.gguf
n-gpu-layers = 999
